// ============================================================
// NexusFlow — Node Registry (50+ integration nodes)
// ============================================================

import { NodeDefinition } from "@/types/workflow";

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // ===================== TRIGGERS =====================
  {
    type: "webhook",
    category: "trigger",
    label: "Webhook Trigger",
    description: "Trigger workflow via incoming HTTP request",
    icon: "Webhook",
    color: "hsl(142, 71%, 45%)",
    inputs: [],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "method", label: "HTTP Method", type: "select", options: [
        { label: "GET", value: "GET" }, { label: "POST", value: "POST" },
        { label: "PUT", value: "PUT" }, { label: "PATCH", value: "PATCH" },
        { label: "DELETE", value: "DELETE" },
      ], defaultValue: "POST" },
      { key: "path", label: "Webhook Path", type: "string", placeholder: "/my-webhook" },
      { key: "authentication", label: "Authentication", type: "select", options: [
        { label: "None", value: "none" }, { label: "Header Token", value: "header" },
        { label: "Basic Auth", value: "basic" }, { label: "HMAC", value: "hmac" },
      ], defaultValue: "none" },
      { key: "responseMode", label: "Response Mode", type: "select", options: [
        { label: "Immediately", value: "immediate" },
        { label: "After Workflow Completes", value: "after" },
      ], defaultValue: "immediate" },
    ],
  },
  {
    type: "schedule",
    category: "trigger",
    label: "Schedule Trigger",
    description: "Trigger workflow on a cron schedule",
    icon: "Clock",
    color: "hsl(142, 71%, 45%)",
    inputs: [],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "cron", label: "Cron Expression", type: "string", placeholder: "0 */5 * * *", required: true },
      { key: "timezone", label: "Timezone", type: "string", defaultValue: "UTC" },
    ],
  },
  {
    type: "email_received",
    category: "trigger",
    label: "Email Trigger",
    description: "Trigger when an email is received",
    icon: "Mail",
    color: "hsl(142, 71%, 45%)",
    inputs: [],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "mailbox", label: "Mailbox", type: "string", defaultValue: "INBOX" },
      { key: "filter", label: "Filter", type: "string", placeholder: "from:user@example.com" },
      { key: "pollInterval", label: "Poll Interval (seconds)", type: "number", defaultValue: 60 },
    ],
    credentialType: "email",
  },
  {
    type: "file_uploaded",
    category: "trigger",
    label: "File Upload Trigger",
    description: "Trigger when a file is uploaded via the API",
    icon: "Upload",
    color: "hsl(142, 71%, 45%)",
    inputs: [],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "allowedTypes", label: "Allowed File Types", type: "string", placeholder: ".csv,.json,.xlsx" },
      { key: "maxSize", label: "Max File Size (MB)", type: "number", defaultValue: 10 },
    ],
  },
  {
    type: "manual",
    category: "trigger",
    label: "Manual Trigger",
    description: "Trigger workflow manually with optional input data",
    icon: "Play",
    color: "hsl(142, 71%, 45%)",
    inputs: [],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "inputSchema", label: "Input Schema (JSON)", type: "json", placeholder: '{"name": "string", "count": "number"}' },
    ],
  },

  // ===================== AI NODES =====================
  {
    type: "llm_chat",
    category: "ai",
    label: "LLM Chat",
    description: "Send a prompt to an LLM and get a response",
    icon: "Bot",
    color: "hsl(270, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "model", label: "Model", type: "select", options: [
        { label: "GPT-4o", value: "gpt-4o" }, { label: "GPT-4o Mini", value: "gpt-4o-mini" },
        { label: "GPT-4 Turbo", value: "gpt-4-turbo" }, { label: "GPT-3.5 Turbo", value: "gpt-3.5-turbo" },
      ], defaultValue: "gpt-4o-mini" },
      { key: "systemPrompt", label: "System Prompt", type: "string", placeholder: "You are a helpful assistant." },
      { key: "userPrompt", label: "User Prompt", type: "expression", required: true, placeholder: "Analyze: {{input.data}}" },
      { key: "temperature", label: "Temperature", type: "number", defaultValue: 0.7, validation: { min: 0, max: 2 } },
      { key: "maxTokens", label: "Max Tokens", type: "number", defaultValue: 1000 },
      { key: "responseFormat", label: "Response Format", type: "select", options: [
        { label: "Text", value: "text" }, { label: "JSON", value: "json" },
      ], defaultValue: "text" },
    ],
    credentialType: "openai",
  },
  {
    type: "summarize",
    category: "ai",
    label: "AI Summarize",
    description: "Summarize text content using AI",
    icon: "FileText",
    color: "hsl(270, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "text", label: "Text to Summarize", type: "expression", required: true },
      { key: "length", label: "Summary Length", type: "select", options: [
        { label: "Brief (1-2 sentences)", value: "brief" },
        { label: "Short (paragraph)", value: "short" },
        { label: "Detailed", value: "detailed" },
      ], defaultValue: "short" },
      { key: "format", label: "Format", type: "select", options: [
        { label: "Paragraph", value: "paragraph" },
        { label: "Bullet Points", value: "bullets" },
      ], defaultValue: "paragraph" },
    ],
    credentialType: "openai",
  },
  {
    type: "classify",
    category: "ai",
    label: "AI Classify",
    description: "Classify text into predefined categories",
    icon: "Tags",
    color: "hsl(270, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "text", label: "Text to Classify", type: "expression", required: true },
      { key: "categories", label: "Categories", type: "array", required: true, placeholder: "Add category..." },
      { key: "multiLabel", label: "Allow Multiple Labels", type: "boolean", defaultValue: false },
      { key: "confidence", label: "Min Confidence", type: "number", defaultValue: 0.7, validation: { min: 0, max: 1 } },
    ],
    credentialType: "openai",
  },
  {
    type: "extract",
    category: "ai",
    label: "AI Extract",
    description: "Extract structured data from unstructured text",
    icon: "Search",
    color: "hsl(270, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "text", label: "Source Text", type: "expression", required: true },
      { key: "schema", label: "Extraction Schema (JSON)", type: "json", required: true,
        placeholder: '{"name": "string", "email": "string", "phone": "string"}' },
      { key: "instructions", label: "Additional Instructions", type: "string" },
    ],
    credentialType: "openai",
  },
  {
    type: "translate",
    category: "ai",
    label: "AI Translate",
    description: "Translate text between languages",
    icon: "Languages",
    color: "hsl(270, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "text", label: "Text to Translate", type: "expression", required: true },
      { key: "sourceLang", label: "Source Language", type: "string", defaultValue: "auto" },
      { key: "targetLang", label: "Target Language", type: "string", required: true, placeholder: "Spanish" },
      { key: "tone", label: "Tone", type: "select", options: [
        { label: "Formal", value: "formal" },
        { label: "Informal", value: "informal" },
        { label: "Technical", value: "technical" },
      ], defaultValue: "formal" },
    ],
    credentialType: "openai",
  },
  {
    type: "sentiment",
    category: "ai",
    label: "Sentiment Analysis",
    description: "Analyze the sentiment of text",
    icon: "Heart",
    color: "hsl(270, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "text", label: "Text to Analyze", type: "expression", required: true },
      { key: "granularity", label: "Granularity", type: "select", options: [
        { label: "Document Level", value: "document" },
        { label: "Sentence Level", value: "sentence" },
      ], defaultValue: "document" },
    ],
    credentialType: "openai",
  },

  // ===================== CONDITION =====================
  {
    type: "condition",
    category: "condition",
    label: "Condition",
    description: "Branch workflow based on conditions",
    icon: "GitBranch",
    color: "hsl(45, 93%, 47%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [
      { id: "true", label: "True", type: "output" },
      { id: "false", label: "False", type: "output" },
    ],
    configSchema: [
      { key: "expression", label: "Condition Expression", type: "expression", required: true,
        placeholder: "{{input.status}} === 'active' && {{input.count}} > 10" },
      { key: "mode", label: "Mode", type: "select", options: [
        { label: "Expression", value: "expression" },
        { label: "Simple Compare", value: "simple" },
      ], defaultValue: "expression" },
      { key: "field", label: "Field (Simple Mode)", type: "expression" },
      { key: "operator", label: "Operator", type: "select", options: [
        { label: "Equals", value: "eq" }, { label: "Not Equals", value: "neq" },
        { label: "Greater Than", value: "gt" }, { label: "Less Than", value: "lt" },
        { label: "Contains", value: "contains" }, { label: "Not Contains", value: "not_contains" },
        { label: "Starts With", value: "starts_with" }, { label: "Ends With", value: "ends_with" },
        { label: "Is Empty", value: "is_empty" }, { label: "Is Not Empty", value: "is_not_empty" },
        { label: "Regex Match", value: "regex" },
      ] },
      { key: "value", label: "Compare Value", type: "expression" },
    ],
  },

  // ===================== LOOP =====================
  {
    type: "loop",
    category: "loop",
    label: "Loop",
    description: "Iterate over an array of items",
    icon: "Repeat",
    color: "hsl(200, 80%, 50%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [
      { id: "item", label: "Current Item", type: "output" },
      { id: "done", label: "Loop Done", type: "output" },
    ],
    configSchema: [
      { key: "array", label: "Array Expression", type: "expression", required: true, placeholder: "{{input.items}}" },
      { key: "batchSize", label: "Batch Size", type: "number", defaultValue: 1 },
      { key: "concurrency", label: "Concurrency", type: "number", defaultValue: 1 },
      { key: "maxIterations", label: "Max Iterations", type: "number", defaultValue: 1000 },
    ],
  },

  // ===================== ERROR HANDLING =====================
  {
    type: "error_handler",
    category: "error",
    label: "Error Handler",
    description: "Handle errors from upstream nodes",
    icon: "AlertTriangle",
    color: "hsl(0, 84%, 60%)",
    inputs: [{ id: "error", label: "Error", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "strategy", label: "Strategy", type: "select", options: [
        { label: "Retry", value: "retry" },
        { label: "Fallback Value", value: "fallback" },
        { label: "Send Notification", value: "notify" },
        { label: "Ignore", value: "ignore" },
        { label: "Stop Workflow", value: "stop" },
      ], required: true },
      { key: "maxRetries", label: "Max Retries", type: "number", defaultValue: 3 },
      { key: "retryDelay", label: "Retry Delay (ms)", type: "number", defaultValue: 1000 },
      { key: "fallbackValue", label: "Fallback Value (JSON)", type: "json" },
      { key: "notificationChannel", label: "Notification Channel", type: "select", options: [
        { label: "Email", value: "email" }, { label: "Slack", value: "slack" },
        { label: "Discord", value: "discord" },
      ] },
      { key: "notificationMessage", label: "Notification Message", type: "expression" },
    ],
  },

  // ===================== INTEGRATION NODES =====================
  {
    type: "http_request",
    category: "action",
    label: "HTTP Request",
    description: "Make an HTTP request to any API",
    icon: "Globe",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "method", label: "Method", type: "select", options: [
        { label: "GET", value: "GET" }, { label: "POST", value: "POST" },
        { label: "PUT", value: "PUT" }, { label: "PATCH", value: "PATCH" },
        { label: "DELETE", value: "DELETE" }, { label: "HEAD", value: "HEAD" },
      ], required: true, defaultValue: "GET" },
      { key: "url", label: "URL", type: "expression", required: true, placeholder: "https://api.example.com/data" },
      { key: "headers", label: "Headers", type: "keyvalue" },
      { key: "queryParams", label: "Query Parameters", type: "keyvalue" },
      { key: "body", label: "Body", type: "json" },
      { key: "bodyType", label: "Body Type", type: "select", options: [
        { label: "JSON", value: "json" }, { label: "Form Data", value: "form" },
        { label: "Raw", value: "raw" }, { label: "None", value: "none" },
      ], defaultValue: "json" },
      { key: "timeout", label: "Timeout (ms)", type: "number", defaultValue: 30000 },
      { key: "followRedirects", label: "Follow Redirects", type: "boolean", defaultValue: true },
    ],
  },
  {
    type: "email_send",
    category: "action",
    label: "Send Email",
    description: "Send an email via SMTP",
    icon: "Send",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "to", label: "To", type: "expression", required: true },
      { key: "cc", label: "CC", type: "expression" },
      { key: "bcc", label: "BCC", type: "expression" },
      { key: "subject", label: "Subject", type: "expression", required: true },
      { key: "body", label: "Body", type: "expression", required: true },
      { key: "isHtml", label: "HTML Email", type: "boolean", defaultValue: false },
    ],
    credentialType: "smtp",
  },
  {
    type: "slack_message",
    category: "action",
    label: "Slack Message",
    description: "Send a message to a Slack channel",
    icon: "MessageSquare",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "channel", label: "Channel", type: "expression", required: true, placeholder: "#general" },
      { key: "text", label: "Message", type: "expression", required: true },
      { key: "blocks", label: "Block Kit Blocks (JSON)", type: "json" },
      { key: "threadTs", label: "Thread Timestamp", type: "expression" },
    ],
    credentialType: "slack",
  },
  {
    type: "discord_message",
    category: "action",
    label: "Discord Message",
    description: "Send a message to a Discord channel",
    icon: "MessageCircle",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "channelId", label: "Channel ID", type: "expression", required: true },
      { key: "content", label: "Message", type: "expression", required: true },
      { key: "embed", label: "Embed (JSON)", type: "json" },
    ],
    credentialType: "discord",
  },
  {
    type: "google_sheets",
    category: "action",
    label: "Google Sheets",
    description: "Read from or write to Google Sheets",
    icon: "Table",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Read Range", value: "read" }, { label: "Append Row", value: "append" },
        { label: "Update Cell", value: "update" }, { label: "Clear Range", value: "clear" },
      ], required: true },
      { key: "spreadsheetId", label: "Spreadsheet ID", type: "expression", required: true },
      { key: "range", label: "Range", type: "string", placeholder: "Sheet1!A1:D10" },
      { key: "data", label: "Data (JSON)", type: "json" },
    ],
    credentialType: "google",
  },
  {
    type: "database_query",
    category: "action",
    label: "Database Query",
    description: "Execute a SQL query against a database",
    icon: "Database",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "dbType", label: "Database Type", type: "select", options: [
        { label: "PostgreSQL", value: "postgres" }, { label: "MySQL", value: "mysql" },
        { label: "SQLite", value: "sqlite" }, { label: "MongoDB", value: "mongodb" },
      ], required: true },
      { key: "query", label: "Query", type: "code", required: true },
      { key: "parameters", label: "Parameters (JSON)", type: "json" },
    ],
    credentialType: "database",
  },
  {
    type: "s3_upload",
    category: "action",
    label: "S3 Upload",
    description: "Upload a file to Amazon S3",
    icon: "CloudUpload",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "bucket", label: "Bucket", type: "expression", required: true },
      { key: "key", label: "Object Key", type: "expression", required: true },
      { key: "content", label: "Content", type: "expression", required: true },
      { key: "contentType", label: "Content Type", type: "string", defaultValue: "application/octet-stream" },
      { key: "acl", label: "ACL", type: "select", options: [
        { label: "Private", value: "private" },
        { label: "Public Read", value: "public-read" },
      ], defaultValue: "private" },
    ],
    credentialType: "aws",
  },
  {
    type: "s3_download",
    category: "action",
    label: "S3 Download",
    description: "Download a file from Amazon S3",
    icon: "CloudDownload",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "bucket", label: "Bucket", type: "expression", required: true },
      { key: "key", label: "Object Key", type: "expression", required: true },
    ],
    credentialType: "aws",
  },
  {
    type: "delay",
    category: "action",
    label: "Delay",
    description: "Wait for a specified duration",
    icon: "Timer",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "duration", label: "Duration (ms)", type: "number", required: true, defaultValue: 1000 },
      { key: "unit", label: "Unit", type: "select", options: [
        { label: "Milliseconds", value: "ms" }, { label: "Seconds", value: "s" },
        { label: "Minutes", value: "m" }, { label: "Hours", value: "h" },
      ], defaultValue: "ms" },
    ],
  },
  {
    type: "set_variable",
    category: "action",
    label: "Set Variable",
    description: "Set a workflow variable",
    icon: "Variable",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "variables", label: "Variables", type: "keyvalue", required: true },
    ],
  },
  {
    type: "code_execute",
    category: "action",
    label: "Execute Code",
    description: "Run custom JavaScript code",
    icon: "Code",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "code", label: "JavaScript Code", type: "code", required: true,
        placeholder: "// Access input data via `input`\nconst result = input.data;\nreturn { processed: result };" },
      { key: "timeout", label: "Timeout (ms)", type: "number", defaultValue: 5000 },
    ],
  },
  {
    type: "json_transform",
    category: "action",
    label: "JSON Transform",
    description: "Transform JSON data using JSONPath or mapping",
    icon: "Braces",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "mapping", label: "Field Mapping", type: "keyvalue", required: true },
      { key: "mode", label: "Mode", type: "select", options: [
        { label: "Map Fields", value: "map" },
        { label: "JSONPath Extract", value: "jsonpath" },
        { label: "Template", value: "template" },
      ], defaultValue: "map" },
      { key: "template", label: "Output Template (JSON)", type: "json" },
    ],
  },
  {
    type: "csv_parse",
    category: "action",
    label: "CSV Parse",
    description: "Parse CSV data into JSON",
    icon: "FileSpreadsheet",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "data", label: "CSV Data", type: "expression", required: true },
      { key: "delimiter", label: "Delimiter", type: "string", defaultValue: "," },
      { key: "hasHeader", label: "Has Header Row", type: "boolean", defaultValue: true },
    ],
  },
  {
    type: "webhook_response",
    category: "action",
    label: "Webhook Response",
    description: "Send a custom response to the webhook caller",
    icon: "Reply",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "statusCode", label: "Status Code", type: "number", defaultValue: 200 },
      { key: "headers", label: "Response Headers", type: "keyvalue" },
      { key: "body", label: "Response Body", type: "expression" },
    ],
  },
  {
    type: "html_extract",
    category: "action",
    label: "HTML Extract",
    description: "Extract data from HTML using CSS selectors",
    icon: "Code2",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "html", label: "HTML Content", type: "expression", required: true },
      { key: "selectors", label: "CSS Selectors", type: "keyvalue", required: true },
      { key: "extractAttribute", label: "Extract Attribute", type: "string", placeholder: "href, src, text" },
    ],
  },
  {
    type: "graphql_request",
    category: "action",
    label: "GraphQL Request",
    description: "Execute a GraphQL query or mutation",
    icon: "Workflow",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "endpoint", label: "Endpoint URL", type: "expression", required: true },
      { key: "query", label: "Query/Mutation", type: "code", required: true },
      { key: "variables", label: "Variables (JSON)", type: "json" },
      { key: "headers", label: "Headers", type: "keyvalue" },
    ],
  },
  {
    type: "redis_command",
    category: "action",
    label: "Redis Command",
    description: "Execute a Redis command",
    icon: "Database",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "command", label: "Command", type: "select", options: [
        { label: "GET", value: "get" }, { label: "SET", value: "set" },
        { label: "DEL", value: "del" }, { label: "HGET", value: "hget" },
        { label: "HSET", value: "hset" }, { label: "LPUSH", value: "lpush" },
        { label: "RPUSH", value: "rpush" }, { label: "LPOP", value: "lpop" },
        { label: "RPOP", value: "rpop" }, { label: "SADD", value: "sadd" },
        { label: "SMEMBERS", value: "smembers" },
      ], required: true },
      { key: "key", label: "Key", type: "expression", required: true },
      { key: "value", label: "Value", type: "expression" },
      { key: "ttl", label: "TTL (seconds)", type: "number" },
    ],
    credentialType: "redis",
  },
  {
    type: "postgres_query",
    category: "action",
    label: "PostgreSQL Query",
    description: "Execute a PostgreSQL query",
    icon: "Database",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "query", label: "SQL Query", type: "code", required: true },
      { key: "parameters", label: "Parameters (JSON array)", type: "json" },
    ],
    credentialType: "postgres",
  },
  {
    type: "mysql_query",
    category: "action",
    label: "MySQL Query",
    description: "Execute a MySQL query",
    icon: "Database",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "query", label: "SQL Query", type: "code", required: true },
      { key: "parameters", label: "Parameters (JSON array)", type: "json" },
    ],
    credentialType: "mysql",
  },
  {
    type: "mongodb_query",
    category: "action",
    label: "MongoDB Query",
    description: "Execute a MongoDB query",
    icon: "Database",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Find", value: "find" }, { label: "Insert", value: "insert" },
        { label: "Update", value: "update" }, { label: "Delete", value: "delete" },
        { label: "Aggregate", value: "aggregate" },
      ], required: true },
      { key: "collection", label: "Collection", type: "expression", required: true },
      { key: "query", label: "Query (JSON)", type: "json" },
      { key: "data", label: "Data (JSON)", type: "json" },
    ],
    credentialType: "mongodb",
  },
  {
    type: "twilio_sms",
    category: "action",
    label: "Send SMS (Twilio)",
    description: "Send an SMS via Twilio",
    icon: "Smartphone",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "to", label: "To Phone Number", type: "expression", required: true },
      { key: "body", label: "Message", type: "expression", required: true },
      { key: "from", label: "From Number", type: "expression" },
    ],
    credentialType: "twilio",
  },
  {
    type: "stripe_charge",
    category: "action",
    label: "Stripe Charge",
    description: "Create a Stripe payment charge",
    icon: "CreditCard",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "amount", label: "Amount (cents)", type: "expression", required: true },
      { key: "currency", label: "Currency", type: "string", defaultValue: "usd" },
      { key: "customerId", label: "Customer ID", type: "expression" },
      { key: "description", label: "Description", type: "expression" },
    ],
    credentialType: "stripe",
  },
  {
    type: "github_api",
    category: "action",
    label: "GitHub API",
    description: "Interact with the GitHub API",
    icon: "Github",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Issue", value: "create_issue" },
        { label: "Create PR", value: "create_pr" },
        { label: "List Repos", value: "list_repos" },
        { label: "Get Repo", value: "get_repo" },
        { label: "Custom API Call", value: "custom" },
      ], required: true },
      { key: "owner", label: "Owner", type: "expression" },
      { key: "repo", label: "Repository", type: "expression" },
      { key: "endpoint", label: "Custom Endpoint", type: "expression" },
      { key: "method", label: "HTTP Method", type: "select", options: [
        { label: "GET", value: "GET" }, { label: "POST", value: "POST" },
        { label: "PUT", value: "PUT" }, { label: "PATCH", value: "PATCH" },
        { label: "DELETE", value: "DELETE" },
      ], defaultValue: "GET" },
      { key: "body", label: "Body (JSON)", type: "json" },
    ],
    credentialType: "github",
  },
  {
    type: "notion_api",
    category: "action",
    label: "Notion API",
    description: "Interact with Notion databases and pages",
    icon: "BookOpen",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Query Database", value: "query_database" },
        { label: "Create Page", value: "create_page" },
        { label: "Update Page", value: "update_page" },
        { label: "Get Page", value: "get_page" },
      ], required: true },
      { key: "databaseId", label: "Database ID", type: "expression" },
      { key: "pageId", label: "Page ID", type: "expression" },
      { key: "filter", label: "Filter (JSON)", type: "json" },
      { key: "properties", label: "Properties (JSON)", type: "json" },
    ],
    credentialType: "notion",
  },
  {
    type: "airtable_api",
    category: "action",
    label: "Airtable API",
    description: "Read and write Airtable records",
    icon: "LayoutGrid",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "List Records", value: "list" },
        { label: "Get Record", value: "get" },
        { label: "Create Record", value: "create" },
        { label: "Update Record", value: "update" },
        { label: "Delete Record", value: "delete" },
      ], required: true },
      { key: "baseId", label: "Base ID", type: "expression", required: true },
      { key: "tableName", label: "Table Name", type: "expression", required: true },
      { key: "recordId", label: "Record ID", type: "expression" },
      { key: "fields", label: "Fields (JSON)", type: "json" },
    ],
    credentialType: "airtable",
  },
  {
    type: "sendgrid_email",
    category: "action",
    label: "SendGrid Email",
    description: "Send email via SendGrid",
    icon: "Mail",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "to", label: "To", type: "expression", required: true },
      { key: "from", label: "From", type: "expression", required: true },
      { key: "subject", label: "Subject", type: "expression", required: true },
      { key: "body", label: "Body", type: "expression", required: true },
      { key: "isHtml", label: "HTML Email", type: "boolean", defaultValue: false },
      { key: "templateId", label: "Template ID", type: "string" },
    ],
    credentialType: "sendgrid",
  },
  {
    type: "telegram_message",
    category: "action",
    label: "Telegram Message",
    description: "Send a Telegram message",
    icon: "Send",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "chatId", label: "Chat ID", type: "expression", required: true },
      { key: "text", label: "Message", type: "expression", required: true },
      { key: "parseMode", label: "Parse Mode", type: "select", options: [
        { label: "None", value: "none" },
        { label: "Markdown", value: "Markdown" },
        { label: "HTML", value: "HTML" },
      ], defaultValue: "Markdown" },
    ],
    credentialType: "telegram",
  },
  {
    type: "pdf_generate",
    category: "action",
    label: "Generate PDF",
    description: "Generate a PDF from HTML",
    icon: "FileText",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "html", label: "HTML Content", type: "expression", required: true },
      { key: "options", label: "PDF Options (JSON)", type: "json" },
    ],
  },
  {
    type: "crypto_encrypt",
    category: "action",
    label: "Encrypt",
    description: "Encrypt data using AES-256",
    icon: "Lock",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "data", label: "Data to Encrypt", type: "expression", required: true },
      { key: "key", label: "Encryption Key", type: "expression", required: true },
    ],
  },
  {
    type: "crypto_decrypt",
    category: "action",
    label: "Decrypt",
    description: "Decrypt AES-256 encrypted data",
    icon: "Unlock",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "data", label: "Encrypted Data", type: "expression", required: true },
      { key: "key", label: "Decryption Key", type: "expression", required: true },
    ],
  },
  {
    type: "jwt_sign",
    category: "action",
    label: "JWT Sign",
    description: "Create a signed JWT token",
    icon: "Shield",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "payload", label: "Payload (JSON)", type: "json", required: true },
      { key: "secret", label: "Secret/Key", type: "expression", required: true },
      { key: "algorithm", label: "Algorithm", type: "select", options: [
        { label: "HS256", value: "HS256" }, { label: "HS384", value: "HS384" },
        { label: "HS512", value: "HS512" }, { label: "RS256", value: "RS256" },
      ], defaultValue: "HS256" },
      { key: "expiresIn", label: "Expires In", type: "string", defaultValue: "1h" },
    ],
  },
  {
    type: "jwt_verify",
    category: "action",
    label: "JWT Verify",
    description: "Verify and decode a JWT token",
    icon: "ShieldCheck",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "token", label: "JWT Token", type: "expression", required: true },
      { key: "secret", label: "Secret/Key", type: "expression", required: true },
    ],
  },
  {
    type: "base64_encode",
    category: "action",
    label: "Base64 Encode",
    description: "Encode data to Base64",
    icon: "Binary",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "data", label: "Data", type: "expression", required: true },
    ],
  },
  {
    type: "base64_decode",
    category: "action",
    label: "Base64 Decode",
    description: "Decode Base64 data",
    icon: "Binary",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "data", label: "Base64 Data", type: "expression", required: true },
    ],
  },
  {
    type: "hash_generate",
    category: "action",
    label: "Generate Hash",
    description: "Generate a hash (MD5, SHA-256, etc.)",
    icon: "Hash",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "data", label: "Data", type: "expression", required: true },
      { key: "algorithm", label: "Algorithm", type: "select", options: [
        { label: "MD5", value: "md5" }, { label: "SHA-1", value: "sha1" },
        { label: "SHA-256", value: "sha256" }, { label: "SHA-512", value: "sha512" },
      ], defaultValue: "sha256" },
    ],
  },
  {
    type: "regex_match",
    category: "action",
    label: "Regex Match",
    description: "Match and extract using regular expressions",
    icon: "Regex",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "text", label: "Input Text", type: "expression", required: true },
      { key: "pattern", label: "Regex Pattern", type: "string", required: true },
      { key: "flags", label: "Flags", type: "string", defaultValue: "g" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Match All", value: "match" },
        { label: "Test (boolean)", value: "test" },
        { label: "Replace", value: "replace" },
      ], defaultValue: "match" },
      { key: "replacement", label: "Replacement", type: "expression" },
    ],
  },
  {
    type: "math_compute",
    category: "action",
    label: "Math Compute",
    description: "Perform mathematical operations",
    icon: "Calculator",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "expression", label: "Math Expression", type: "expression", required: true,
        placeholder: "{{input.a}} * {{input.b}} + 100" },
    ],
  },
  {
    type: "xml_parse",
    category: "action",
    label: "XML Parse",
    description: "Parse XML data into JSON",
    icon: "FileCode",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "data", label: "XML Data", type: "expression", required: true },
    ],
  },
  {
    type: "hubspot_api",
    category: "action",
    label: "HubSpot API",
    description: "Interact with HubSpot CRM",
    icon: "Users",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Contact", value: "create_contact" },
        { label: "Update Contact", value: "update_contact" },
        { label: "Get Contact", value: "get_contact" },
        { label: "List Contacts", value: "list_contacts" },
        { label: "Create Deal", value: "create_deal" },
      ], required: true },
      { key: "data", label: "Data (JSON)", type: "json" },
    ],
    credentialType: "hubspot",
  },
  {
    type: "salesforce_api",
    category: "action",
    label: "Salesforce API",
    description: "Interact with Salesforce CRM",
    icon: "Cloud",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Query (SOQL)", value: "query" },
        { label: "Create Record", value: "create" },
        { label: "Update Record", value: "update" },
        { label: "Delete Record", value: "delete" },
      ], required: true },
      { key: "objectType", label: "Object Type", type: "string", placeholder: "Account, Contact, Lead..." },
      { key: "query", label: "SOQL Query", type: "code" },
      { key: "data", label: "Record Data (JSON)", type: "json" },
    ],
    credentialType: "salesforce",
  },
  {
    type: "jira_api",
    category: "action",
    label: "Jira API",
    description: "Interact with Jira issues and projects",
    icon: "Bug",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Issue", value: "create_issue" },
        { label: "Update Issue", value: "update_issue" },
        { label: "Get Issue", value: "get_issue" },
        { label: "Search Issues (JQL)", value: "search" },
        { label: "Add Comment", value: "add_comment" },
      ], required: true },
      { key: "projectKey", label: "Project Key", type: "expression" },
      { key: "issueKey", label: "Issue Key", type: "expression" },
      { key: "jql", label: "JQL Query", type: "string" },
      { key: "data", label: "Data (JSON)", type: "json" },
    ],
    credentialType: "jira",
  },
  {
    type: "mailchimp_api",
    category: "action",
    label: "Mailchimp API",
    description: "Manage Mailchimp lists and campaigns",
    icon: "Mail",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Add Subscriber", value: "add_subscriber" },
        { label: "Remove Subscriber", value: "remove_subscriber" },
        { label: "List Members", value: "list_members" },
        { label: "Send Campaign", value: "send_campaign" },
      ], required: true },
      { key: "listId", label: "List/Audience ID", type: "expression" },
      { key: "email", label: "Email", type: "expression" },
      { key: "data", label: "Data (JSON)", type: "json" },
    ],
    credentialType: "mailchimp",
  },
  {
    type: "zendesk_api",
    category: "action",
    label: "Zendesk API",
    description: "Manage Zendesk tickets and users",
    icon: "Headphones",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Ticket", value: "create_ticket" },
        { label: "Update Ticket", value: "update_ticket" },
        { label: "Get Ticket", value: "get_ticket" },
        { label: "List Tickets", value: "list_tickets" },
        { label: "Add Comment", value: "add_comment" },
      ], required: true },
      { key: "ticketId", label: "Ticket ID", type: "expression" },
      { key: "data", label: "Data (JSON)", type: "json" },
    ],
    credentialType: "zendesk",
  },
  {
    type: "whatsapp_message",
    category: "action",
    label: "WhatsApp Message",
    description: "Send a WhatsApp message",
    icon: "MessageSquare",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "to", label: "To Phone Number", type: "expression", required: true },
      { key: "message", label: "Message", type: "expression", required: true },
      { key: "templateName", label: "Template Name", type: "string" },
    ],
    credentialType: "whatsapp",
  },
  {
    type: "image_resize",
    category: "action",
    label: "Resize Image",
    description: "Resize an image to specified dimensions",
    icon: "Image",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "imageUrl", label: "Image URL/Data", type: "expression", required: true },
      { key: "width", label: "Width", type: "number", required: true },
      { key: "height", label: "Height", type: "number", required: true },
      { key: "format", label: "Output Format", type: "select", options: [
        { label: "PNG", value: "png" }, { label: "JPEG", value: "jpeg" },
        { label: "WebP", value: "webp" },
      ], defaultValue: "png" },
    ],
  },
  {
    type: "qr_generate",
    category: "action",
    label: "Generate QR Code",
    description: "Generate a QR code image",
    icon: "QrCode",
    color: "hsl(210, 76%, 55%)",
    inputs: [{ id: "input", label: "Input", type: "input" }],
    outputs: [{ id: "output", label: "Output", type: "output" }],
    configSchema: [
      { key: "data", label: "Data/URL", type: "expression", required: true },
      { key: "size", label: "Size (px)", type: "number", defaultValue: 256 },
      { key: "format", label: "Format", type: "select", options: [
        { label: "PNG", value: "png" }, { label: "SVG", value: "svg" },
      ], defaultValue: "png" },
    ],
  },
];

export function getNodeDefinition(type: string): NodeDefinition | undefined {
  return NODE_DEFINITIONS.find((n) => n.type === type);
}

export function getNodesByCategory(category: string): NodeDefinition[] {
  return NODE_DEFINITIONS.filter((n) => n.category === category);
}

export const NODE_CATEGORIES = [
  { id: "trigger", label: "Triggers", icon: "Zap", color: "hsl(142, 71%, 45%)" },
  { id: "ai", label: "AI Nodes", icon: "Brain", color: "hsl(270, 76%, 55%)" },
  { id: "action", label: "Actions", icon: "Play", color: "hsl(210, 76%, 55%)" },
  { id: "condition", label: "Logic", icon: "GitBranch", color: "hsl(45, 93%, 47%)" },
  { id: "loop", label: "Loops", icon: "Repeat", color: "hsl(200, 80%, 50%)" },
  { id: "error", label: "Error Handling", icon: "AlertTriangle", color: "hsl(0, 84%, 60%)" },
];
